name: daily_bite
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  #core packages statement/api
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  meta: ^1.15.0
  #navigation in app
  go_router: ^14.6.3
  particles_flutter: ^1.0.1
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

